### ISSUE TITLE
Donor button

### ISSUE THREAD

**Issue by harbolkn** [climbcrux/climbcrux.github.io#3]
# Summary

A general donation button should be somewhere on the website so people can make donations without becoming a member.

- [x] Feature
- [ ] Bug

# Feature Request
### Description

There should be a general donation button somewhere on the website. When a website visitor chooses to donate to CRUX via the general donation button they should be able to specify how much they wish to donate. They should then be able to pay via our GiveLively donation page.

After payment is complete they should receive a success message thanking them for their donation.
A thank you email should also be triggered which thanks the visitor for donating to CRUX. The email should include tax information and should serve as a tax receipt.

### Value
This will allow us to accept donations for people who are either already CRUX members and wish to give more, or who do not wish to join as a member but would still like to give.

### Feature Priority
- [ ] Low
- [x] Medium
- [ ] High

### Contributors

Please fill who will be contributing to this feature. If you are unsure of who will be helping making this feature a reality please reach out via Slack to #website and we can attempt to find someone to support.

- *Content writer:* [who will write the feature content?]
- *Designer:* [who will be providing the design for this feature?]
- *Photo Editor:* [who will be selecting any photo assets?]
- *Other:* [anyone else helping contribute?]

**Comment by danieljosephparker** [comment]
@harbolkn Please consult with Chandler. This feature request originated with her originally, so I want to make sure she has creative input.

**Comment by harbolkn** [comment]
### How we're doing this

Chandler has configured a GiveLively donor page for CRUX. [@Chandleratk can you link it here?]

The plan right now it to:

1. Change the text of the "Join" button to something more ambiguous which implies getting involved with CRUX

    Potential Language:
    - "Get Involved"
    - "Give"
    - "Support"
    - "Contribute"
 
2. When a user clicks this button it will take them to a "Ways to Contribute" page, which includes:

    - Blurb on Membership & Link to Join
    - Blurb on Donating & Link to GiveLively page

## Future Development

1. The 2nd iteration of this project will be switching the CRUX membership payment processing over to Stripe. With will support Credit Card transactions for CRUXers who don't have PayPal.

2. The final iteration will be adding "Volunteer" information to the contribute page

Separate issues will be opened for these projects.

**Comment by Chandleratk** [comment]
Here is the link for the GiveLively page: https://secure.givelively.org/donate/crux-climbing-inc

**Comment by harbolkn** [comment]
This is live on the site now: https://climbcrux.org/get-involved
